# Generated by Django 3.2.3 on 2021-05-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Description', '0002_auto_20210520_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='FieldName',
            new_name='fieldName',
        ),
    ]
