# Generated by Django 3.2.3 on 2021-05-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugReport', '0002_auto_20210521_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='site_id',
            field=models.CharField(default='index', max_length=200),
        ),
    ]
