# Generated by Django 3.2.3 on 2021-05-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugReport', '0003_alter_bug_site_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('fixed', 'fixed'), ('pending', 'pending')], default='pending', max_length=100),
        ),
    ]
